name: qr_scan_app
description: "Aplicación Flutter para escanear codigos de QR con autenticación biométrica."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  melos: ^6.3.2
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  go_router: ^14.3.0
  flutter_svg: ^2.0.4
  biometric_auth:
    path: ../../packages/biometric_auth
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/
