name: biometric_auth
description: "Paquete para manejar la autenticación biométrica en la app QR."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  pigeon: ^24.2.1
  local_auth: ^2.3.0
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
